### ISSUE TITLE
NPC spells not working

### ISSUE THREAD

**Issue by ILikeCoolThings** [MrVauxs/pf2e-jb2a-macros#18]
Whenever a NPC casts a spell that has an AA entry, the below error is put into the console and no animation is played.
This error can be repeated with a Water Mephit by casting Acid Arrow.

Just to add... melee attacks and equipment work just fine. Seems like it is spells only

```js
foundry.js:319 TypeError: Cannot read properties of undefined (reading 'runJB2Apf2eMacro')
[Detected 2 packages: pf2e-jb2a-macros, system:pf2e]
    at module.js:198
    at Function._call (foundry.js:294)
    at Function.call (foundry.js:279)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:10013)
    at async ClientDatabaseBackend._createDocuments (foundry.js:9930)
    at async Function.createDocuments (document.mjs:338)
    at async Function.create (document.mjs:439)
    at async SpellcastingEntryPF2e.cast (main.bundle.js:1)

**Comment by MrVauxs** [comment]
Fixed in 1.10.5

**Comment by ILikeCoolThings** [comment]
It looks like that they are still broken... Both PCs and NPCs. This is the console error:

```js
foundry.js:319 TypeError: Cannot read properties of undefined (reading 'pf2eJB2AMacros')
[Detected 3 packages: pf2e-jb2a-macros, system:pf2e, token-action-hud]
    at module.js:198
    at Function._call (foundry.js:294)
    at Function.call (foundry.js:279)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:10013)
    at async ClientDatabaseBackend._createDocuments (foundry.js:9930)
    at async Function.createDocuments (document.mjs:338)
    at async Function.create (document.mjs:439)
    at async SpellcastingEntryPF2e.cast (main.bundle.js:1)
    at async RollHandlerBasePf2e._rollSpell (bundle.min.js:1)
    at async RollHandlerBasePf2e._handleMacros (bundle.min.js:1)
    at async RollHandlerBasePf2e.doHandleActionEvent (bundle.min.js:1)

**Comment by MrVauxs** [comment]
Disable debugging if you have it enabled. I'll look into it when I have
free time (read: 2 days).

niedz., 4 wrz 2022, 02:41 użytkownik MotherOfGod ***@***.***>
napisał:

**Comment by ILikeCoolThings** [comment]
Not a problem, take your time.

And debugging is disabled.
